version: "3.7"
services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./web/src/:/app/

  worker_scheduler:
    build:
      context: ./worker_scheduler/
      dockerfile: ./Dockerfile
    volumes:
      # - ./NexaCore/nexa:/opt/conda/lib/python3.7/site-packages/nexa
      - ./worker_scheduler/src/:/app/
    restart: always
    command: weather_worker.py
  
  device:
    build:
      context: ./device
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./device/src/:/app
    restart: always
